### ISSUE TITLE
Discussion: Do we need any more information to finish the requirements doc?

### ISSUE THREAD

**Issue by erinnmclaughlin** [blazorbuilds/Blazing-Checkers#1]
I have edited the requirements document to simulate client answers to the initial questions. If anyone thinks of other questions to ask, drop them in here! We can compile everything into a single project plan at the end of the week.

**Comment by markmahowald** [comment]
Hello, 

Thanks so much for doing this!
I was curious what kind of security / password encryption will be used in this application. I am new to the world of c# web development and was hoping that this project might cover security because I am not sure where to even start on the topic. 

Thanks, 
Mark Mahowald

**Comment by erinnmclaughlin** [comment]
Hi @markmahowald! I'm going to go with the default [Identity System](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-3.1) that comes with ASP.NET Core. Initially I was thinking of going a more "manual" route but I think I'm going to just leave that for future projects. We'll still spend some time customizing things though, so it won't be a total black-box solution!

**Comment by markmahowald** [comment]
Sounds good. Ive never worked with the default Identity System. Thanks!
